// This file was generated by build.py, don't modify it manually.

#pragma once

#define VERSION_STR         "0.1.1"

#define MAJOR_VERSION       0
#define MINOR_VERSION       1
#define BUILD_NUM           1

#define VERSION             100100
